
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: payroll_db
          POSTGRES_USER: payroll_user
          POSTGRES_PASSWORD: payroll_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U payroll_user -d payroll_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Backend deps
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django migrate
        env:
          POSTGRES_DB: payroll_db
          POSTGRES_USER: payroll_user
          POSTGRES_PASSWORD: payroll_pass
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          SECRET_KEY: dummy
        working-directory: ./backend
        run: |
          python manage.py migrate
          python - <<'PY'
          import os
          import django
          os.environ.setdefault("DJANGO_SETTINGS_MODULE","payroll_backend.settings")
          django.setup()
          print("Django OK")
          PY

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Frontend deps & build
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: http://localhost:8000
        run: |
          npm ci || npm install
          npm run build
